### ISSUE TITLE
Frame does not expand when Email-Tracking is expanded

### ISSUE THREAD

**Issue by klou** [yathit/sugarcrm-gmail-chrome-extension#3]
Steps to duplicate:
1. Search for an Account, Note, Contact, etc. (or populate any tab with data, so Create, Feeds, etc.)
2. Expand the Email tracking dropdown/field

![yathit frame](https://cloud.githubusercontent.com/assets/1377378/6755875/68568eb0-cee3-11e4-9a82-622cc87f83cc.jpg)

**Comment by yathit** [comment]
This one I cannot reproduce. Did your account has some tracking result?

**Comment by klou** [comment]
No, no tracking results.  Just tried again with Chrome 41.0.2272.101 m (64-bit)

**Comment by yathit** [comment]
Thanks for the report. This is fixed by displaying "No result to display" in rel 3.1.5.
