### ISSUE TITLE
Displaying blank 'primary' fields defaults to id

### ISSUE THREAD

**Issue by klou** [yathit/sugarcrm-gmail-chrome-extension#4]
I have some imported data that isn't quite correct, i.e. Notes with a blank subject line.

Displays of this note Subject (in the search) instead insert the notes.id.  Is this intentional?
![yathit id](https://cloud.githubusercontent.com/assets/1377378/6756237/af8cd832-cee5-11e4-9e76-00305f3129ef.jpg)

**Comment by yathit** [comment]
Yes by design, record label is either 'name' or 'id' field value. If you have better idea, please suggest. See detail https://github.com/yathit/sugarcrm/blob/master/src/ydn/crm/sugarcrm/record.js#L310
